M48
; DRILL file {KiCad 7.0.9} date Sat 02 Mar 2024 17:11:19
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-02T17:11:19+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X2.6399Y-3.9987
X2.6399Y-4.2263
T2
X3.0Y-2.8
X3.2Y-2.8
T0
M30
